### ISSUE TITLE
User `subtree` instead of `submodule`.

### ISSUE THREAD

**Issue by mysterycommand** [pwmckenna/generator-travis-ci#3]
The [Yeoman Deployment](https://github.com/yeoman/yeoman/wiki/Deployment) instructions seem to recommend `subtree` over `submodule`. As does [this article from Atlassian](http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/).

Consider switching?

**Comment by pwmckenna** [comment]
The use of submodule is a complete mistake...I need to rewrite it to just do a git clone of the gh-pages branch. Its just there because I need both gh-pages and master branch code available at the same time (you can't build in master, then checkout gh-pages cleanly). Their recommendations are really for people committing to gh-pages manually, so the submodule or subtree needs to be committed to the master branch. In this case the goal was to not actually affect the repo, so all the changes that happen in the travis script disappear when the travis vm instance disappears.
